l_english:

 # Format for year display
 DS_LOC_DISPLAY_YEAR: "$VALUE|0$"
 
 # Text to show for each respective era
 DS_LOC_DISPLAY_ERA_01: "E1"
 DS_LOC_DISPLAY_ERA_02: "E2"
 DS_LOC_DISPLAY_ERA_03: "E3"
 DS_LOC_DISPLAY_ERA_04: "E4"
 DS_LOC_DISPLAY_ERA_05: "E5"
 DS_LOC_DISPLAY_ERA_06: "E6"
 DS_LOC_DISPLAY_ERA_07: "E7"
 DS_LOC_DISPLAY_ERA_08: "E8"
 DS_LOC_DISPLAY_ERA_09: "E9"
 DS_LOC_DISPLAY_ERA_10: "E10"
 DS_LOC_DISPLAY_ERA_FALLBACK: "FB" # Shows if somehow everything went tits up